// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: NWorkQueue.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace NWorkQueue.Models {
  /// <summary>
  /// The service definition.
  /// </summary>
  public static partial class QueueApi
  {
    static readonly string __ServiceName = "greet.QueueApi";

    static readonly grpc::Marshaller<global::NWorkQueue.Models.CreateQueueRequest> __Marshaller_greet_CreateQueueRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::NWorkQueue.Models.CreateQueueRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::NWorkQueue.Models.CreateQueueResponse> __Marshaller_greet_CreateQueueResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::NWorkQueue.Models.CreateQueueResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::NWorkQueue.Models.InitializeStorageRequest> __Marshaller_greet_InitializeStorageRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::NWorkQueue.Models.InitializeStorageRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::NWorkQueue.Models.InitializeStorageResponse> __Marshaller_greet_InitializeStorageResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::NWorkQueue.Models.InitializeStorageResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::NWorkQueue.Models.DeleteQueueByIdRequest> __Marshaller_greet_DeleteQueueByIdRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::NWorkQueue.Models.DeleteQueueByIdRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::NWorkQueue.Models.DeleteQueueByIdResponse> __Marshaller_greet_DeleteQueueByIdResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::NWorkQueue.Models.DeleteQueueByIdResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::NWorkQueue.Models.DeleteQueueByNameRequest> __Marshaller_greet_DeleteQueueByNameRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::NWorkQueue.Models.DeleteQueueByNameRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::NWorkQueue.Models.DeleteQueueByNameResponse> __Marshaller_greet_DeleteQueueByNameResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::NWorkQueue.Models.DeleteQueueByNameResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::NWorkQueue.Models.CreateQueueRequest, global::NWorkQueue.Models.CreateQueueResponse> __Method_CreateQueue = new grpc::Method<global::NWorkQueue.Models.CreateQueueRequest, global::NWorkQueue.Models.CreateQueueResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CreateQueue",
        __Marshaller_greet_CreateQueueRequest,
        __Marshaller_greet_CreateQueueResponse);

    static readonly grpc::Method<global::NWorkQueue.Models.InitializeStorageRequest, global::NWorkQueue.Models.InitializeStorageResponse> __Method_InitializeStorage = new grpc::Method<global::NWorkQueue.Models.InitializeStorageRequest, global::NWorkQueue.Models.InitializeStorageResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "InitializeStorage",
        __Marshaller_greet_InitializeStorageRequest,
        __Marshaller_greet_InitializeStorageResponse);

    static readonly grpc::Method<global::NWorkQueue.Models.DeleteQueueByIdRequest, global::NWorkQueue.Models.DeleteQueueByIdResponse> __Method_DeleteQueueById = new grpc::Method<global::NWorkQueue.Models.DeleteQueueByIdRequest, global::NWorkQueue.Models.DeleteQueueByIdResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "DeleteQueueById",
        __Marshaller_greet_DeleteQueueByIdRequest,
        __Marshaller_greet_DeleteQueueByIdResponse);

    static readonly grpc::Method<global::NWorkQueue.Models.DeleteQueueByNameRequest, global::NWorkQueue.Models.DeleteQueueByNameResponse> __Method_DeleteQueueByName = new grpc::Method<global::NWorkQueue.Models.DeleteQueueByNameRequest, global::NWorkQueue.Models.DeleteQueueByNameResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "DeleteQueueByName",
        __Marshaller_greet_DeleteQueueByNameRequest,
        __Marshaller_greet_DeleteQueueByNameResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::NWorkQueue.Models.NWorkQueueReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of QueueApi</summary>
    [grpc::BindServiceMethod(typeof(QueueApi), "BindService")]
    public abstract partial class QueueApiBase
    {
      public virtual global::System.Threading.Tasks.Task<global::NWorkQueue.Models.CreateQueueResponse> CreateQueue(global::NWorkQueue.Models.CreateQueueRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::NWorkQueue.Models.InitializeStorageResponse> InitializeStorage(global::NWorkQueue.Models.InitializeStorageRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::NWorkQueue.Models.DeleteQueueByIdResponse> DeleteQueueById(global::NWorkQueue.Models.DeleteQueueByIdRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::NWorkQueue.Models.DeleteQueueByNameResponse> DeleteQueueByName(global::NWorkQueue.Models.DeleteQueueByNameRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for QueueApi</summary>
    public partial class QueueApiClient : grpc::ClientBase<QueueApiClient>
    {
      /// <summary>Creates a new client for QueueApi</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public QueueApiClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for QueueApi that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public QueueApiClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected QueueApiClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected QueueApiClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::NWorkQueue.Models.CreateQueueResponse CreateQueue(global::NWorkQueue.Models.CreateQueueRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateQueue(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::NWorkQueue.Models.CreateQueueResponse CreateQueue(global::NWorkQueue.Models.CreateQueueRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CreateQueue, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::NWorkQueue.Models.CreateQueueResponse> CreateQueueAsync(global::NWorkQueue.Models.CreateQueueRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateQueueAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::NWorkQueue.Models.CreateQueueResponse> CreateQueueAsync(global::NWorkQueue.Models.CreateQueueRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CreateQueue, null, options, request);
      }
      public virtual global::NWorkQueue.Models.InitializeStorageResponse InitializeStorage(global::NWorkQueue.Models.InitializeStorageRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return InitializeStorage(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::NWorkQueue.Models.InitializeStorageResponse InitializeStorage(global::NWorkQueue.Models.InitializeStorageRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_InitializeStorage, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::NWorkQueue.Models.InitializeStorageResponse> InitializeStorageAsync(global::NWorkQueue.Models.InitializeStorageRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return InitializeStorageAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::NWorkQueue.Models.InitializeStorageResponse> InitializeStorageAsync(global::NWorkQueue.Models.InitializeStorageRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_InitializeStorage, null, options, request);
      }
      public virtual global::NWorkQueue.Models.DeleteQueueByIdResponse DeleteQueueById(global::NWorkQueue.Models.DeleteQueueByIdRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteQueueById(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::NWorkQueue.Models.DeleteQueueByIdResponse DeleteQueueById(global::NWorkQueue.Models.DeleteQueueByIdRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_DeleteQueueById, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::NWorkQueue.Models.DeleteQueueByIdResponse> DeleteQueueByIdAsync(global::NWorkQueue.Models.DeleteQueueByIdRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteQueueByIdAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::NWorkQueue.Models.DeleteQueueByIdResponse> DeleteQueueByIdAsync(global::NWorkQueue.Models.DeleteQueueByIdRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_DeleteQueueById, null, options, request);
      }
      public virtual global::NWorkQueue.Models.DeleteQueueByNameResponse DeleteQueueByName(global::NWorkQueue.Models.DeleteQueueByNameRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteQueueByName(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::NWorkQueue.Models.DeleteQueueByNameResponse DeleteQueueByName(global::NWorkQueue.Models.DeleteQueueByNameRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_DeleteQueueByName, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::NWorkQueue.Models.DeleteQueueByNameResponse> DeleteQueueByNameAsync(global::NWorkQueue.Models.DeleteQueueByNameRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteQueueByNameAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::NWorkQueue.Models.DeleteQueueByNameResponse> DeleteQueueByNameAsync(global::NWorkQueue.Models.DeleteQueueByNameRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_DeleteQueueByName, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override QueueApiClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new QueueApiClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(QueueApiBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_CreateQueue, serviceImpl.CreateQueue)
          .AddMethod(__Method_InitializeStorage, serviceImpl.InitializeStorage)
          .AddMethod(__Method_DeleteQueueById, serviceImpl.DeleteQueueById)
          .AddMethod(__Method_DeleteQueueByName, serviceImpl.DeleteQueueByName).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, QueueApiBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_CreateQueue, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::NWorkQueue.Models.CreateQueueRequest, global::NWorkQueue.Models.CreateQueueResponse>(serviceImpl.CreateQueue));
      serviceBinder.AddMethod(__Method_InitializeStorage, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::NWorkQueue.Models.InitializeStorageRequest, global::NWorkQueue.Models.InitializeStorageResponse>(serviceImpl.InitializeStorage));
      serviceBinder.AddMethod(__Method_DeleteQueueById, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::NWorkQueue.Models.DeleteQueueByIdRequest, global::NWorkQueue.Models.DeleteQueueByIdResponse>(serviceImpl.DeleteQueueById));
      serviceBinder.AddMethod(__Method_DeleteQueueByName, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::NWorkQueue.Models.DeleteQueueByNameRequest, global::NWorkQueue.Models.DeleteQueueByNameResponse>(serviceImpl.DeleteQueueByName));
    }

  }
}
#endregion
